apiVersion: batch/v1
kind: Job
metadata:
  name: gitleaks-scan
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gitleaks
          image: zricethezav/gitleaks:v8.17.0
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: ["sh", "-c"]
          args:
            - |
              echo "démarrage du scan gitleaks"
              git clone https://$GITHUB_TOKEN@github.com/rhood00/sonar10.git /tmp/repo
              cd /tmp/repo
              gitleaks detect --source=. --report-path=/tmp/gitleaks-report.json
              echo "résultat du scan gitleaks"
              cat /tmp/gitleaks-report.json
